// Copyright 2025 Robert Williamson
//
// Licensed under the MIT License;
// You may not used this file except in compliance with the License.
// You may obtain a copy of the License at
//
//       https://opensource.org/license/mit
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#ifndef LRU_CACHE_LRU_CACHE_INTERNAL_MACROS_HPP
#define LRU_CACHE_LRU_CACHE_INTERNAL_MACROS_HPP

#ifdef _MSVC_LANG
#define LRU_CACHE_STD_CPP _MSVC_LANG
#else
#define LRU_CACHE_STD_CPP __cplusplus
#endif

#define LRU_CACHE_HAS_CXX_11 (LRU_CACHE_STD_CPP >= 201103L)
#define LRU_CACHE_HAS_CXX_14 (LRU_CACHE_STD_CPP >= 201402L)
#define LRU_CACHE_HAS_CXX_17 (LRU_CACHE_STD_CPP >= 201703L)
#define LRU_CACHE_HAS_CXX_20 (LRU_CACHE_STD_CPP >= 202002L)
#define LRU_CACHE_HAS_CXX_23 (LRU_CACHE_STD_CPP >= 202302L)

#if LRU_CACHE_HAS_CXX_23
#define LRU_CACHE_STATIC_CALL static
#define LRU_CACHE_STATIC_CALL_CONST
#else
#define LRU_CACHE_STATIC_CALL
#define LRU_CACHE_STATIC_CALL_CONST const
#endif

#if LRU_CACHE_HAS_CXX_14
#define LRU_CACHE_CONSTEXPR_14 constexpr
#else
#define LRU_CACHE_CONSTEXPR_14
#endif

#if LRU_CACHE_HAS_CXX_17
#define LRU_CACHE_CONSTEXPR_17 constexpr
#else
#define LRU_CACHE_CONSTEXPR_17
#endif

#if LRU_CACHE_HAS_CXX_20
#define LRU_CACHE_CONSTEXPR_20 constexpr
#else
#define LRU_CACHE_CONSTEXPR_20
#endif

#define LRU_CACHE_NODISCARD [[nodiscard]]

#ifdef LRU_CACHE_NO_CHECKS
#define LRU_CACHE_ASSERT(...)
#else
#include <cassert>
#define LRU_CACHE_ASSERT(...) assert(__VA_ARGS__)
#endif

#endif // LRU_CACHE_LRU_CACHE_INTERNAL_MACROS_HPP
